config/routes.rb
# Rails.application.routes.draw do
#   # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

#   # Defines the root path route ("/")
#   # root "articles#index"
#   resources :clients do
#     resources :transactions, only: %i[new show index] do
#       post 'transactions/create_expense', to: 'transactions#create_expense', as: :create_expense
#       post 'transactions/create_payment', to: 'transactions#create_payment', as: :create_payment
#       delete 'transactions/:id', to: 'transactions#destroy', as: :destroy_transaction
#     end
#   end

#   root 'clients#new'
# end

Rails.application.routes.draw do
  resources :clients do
    get 'transactions/new', to: 'transactions#new'
    post 'transactions/create_expense', to: 'transactions#create_expense', as: :create_expense
    post 'transactions/create_payment', to: 'transactions#create_payment', as: :create_payment
    delete 'transactions/:id', to: 'transaction#destroy', as: :destroy_transaction
  end

  root 'clients#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
require 'bigdecimal'

class Client < ApplicationRecord
  has_many :expenses
  has_many :payments

  validates :first_name, presence: true
  validates :last_name, presence: true

  before_create :set_default_balance

  def credit(amount)
    amount_as_decimal = BigDecimal(amount.to_s) if valid_numeric?(amount)
    self.balance += amount_as_decimal if amount_as_decimal
    save
  end

  def debit(amount)
    amount_as_decimal = BigDecimal(amount.to_s) if valid_numeric?(amount)
    if amount_as_decimal && self.balance >= amount_as_decimal
      self.balance -= amount_as_decimal
      save
    else
      errors.add(:balance, "Insufficient balance")
      false
    end
  end

  private

  def valid_numeric?(value)
    Float(value)
    true
  rescue ArgumentError, TypeError
    false
  end

  def set_default_balance
    self.balance ||= BigDecimal('0.0')
  end
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :client

end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :client
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def new
    @client = Client.new
  end

  def index
    @clients = Client.all
  end

  def show
    @client = Client.find(params[:id])
    @transactions = @client.expenses + @client.payments
    @transactions.sort_by(&:created_at).reverse!
  end

  def create
    @client = Client.new(client_params)

    if @client.save
      flash[:notice] = 'Client was successfully created.'

      redirect_to clients_path
    else
      render :new
    end
  end

  def update; end

  private

  def client_params
    params.require(:client).permit(:first_name, :last_name)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  def new
    @client = Client.find(params[:client_id])
    if params[:transaction_type] == 'expense'
      @expense = Expense.new
      # @expense.amount = 0 # Set a default value for amount
      # @expense.date = Date.current # Set a default value for date
    else
      @payment = Payment.new
      # @payment.amount = 0 # Set a default value for amount
      # @payment.date = Date.current # Set a default value for date
    end
  end

  def show
    @client = Client.find(params[:client_id])
    transaction_type = params[:transaction_type]

    if transaction_type == 'expense'
      @transaction = Expense.find(params[:id])
    elsif transaction_type == 'payment'
      @transaction = Payment.find(params[:id])
    else
      render json: { error: 'Invalid transaction type' }, status: :unprocessable_entity
    end
  rescue ActiveRecord::RecordNotFound
    render json: { error: 'Transaction not found' }, status: :not_found
  end

  def index
    @client = Client.find(params[:client_id])
    @transactions = @client.expenses + @client.payments
  end

  def create_expense
    client = Client.find(params[:client_id])
    amount = params[:amount]

    ActiveRecord::Base.transaction do
      client.credit(amount)
      Expense.create!(client: client, amount: amount)
    end

    redirect_to client_path(client)
  rescue ActiveRecord::RecordNotFound
    render json: { error: 'User or client not found' }, status: :not_found
  rescue ActiveRecord::RecordInvalid => e
    render json: { error: e.message }, status: :unprocessable_entity
  end

  def create_payment
    client = Client.find(params[:client_id])
    amount = params[:amount]

    ActiveRecord::Base.transaction do
      client.debit(amount)
      Payment.create!(client: client, amount: amount)
    end

    redirect_to client_path(client)
  rescue ActiveRecord::RecordNotFound
    render json: { error: 'User or client not found' }, status: :not_found
  rescue ActiveRecord::RecordInvalid => e
    render json: { error: e.message }, status: :unprocessable_entity
  end

  def destroy
    transaction_type = params[:transaction_type]
    transaction_id = params[:id]

    begin
      transaction = transaction_type == 'expense' ? Expense.find(transaction_id) : Payment.find(transaction_id)
      client = transaction.client

      ActiveRecord::Base.transaction do
        client.credit(transaction.amount) if transaction_type == 'expense'
        client.debit(transaction.amount) if transaction_type == 'payment'
        transaction.destroy
      end

      redirect_to client_path(client)
    rescue ActiveRecord::RecordNotFound
      render json: { error: 'Transaction not found' }, status: :not_found
    rescue ActiveRecord::RecordInvalid => e
      render json: { error: e.message }, status: :unprocessable_entity
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/clients/index.html.erb
<p>...Find me on app/views/clients/index...</p>

<h3>Clients List</h3>
<ol>
  <% @clients.each do |client| %>
    <li>
      <p><%= link_to client.last_name, client%></p>
    </li>
  <% end %>
</ol>

<%= link_to "New Client", root_path, class:"btn btn-primary" %>

app/views/clients/new.html.erb
<p>..Find me on app/views/clients/new...</p>
<div class="m-3 new-client-form">
  <h3>New Client</h3>
  <%= form_with(model: @client, url: clients_path, method: :post) do |form| %>
    <div class="form-group">
      <%= form.label :first_name %>
      <%= form.text_field :first_name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :last_name %>
      <%= form.text_field :last_name, class: 'form-control' %>
    </div>

    <%= form.submit 'Create Client', class: 'mt-3 btn btn-primary' %>
  <% end %>
</div>

app/views/clients/show.html.erb
<p>...Find me on app/views/clients/show</p>
<h3>Client Details</h3>


<h3>Transaction History for <%= @client.last_name %>, <%= @client.first_name %></h3>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Description</th>
      <th>Date</th>
      <th>Type</th>
    </tr>
  </thead>
  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.amount.to_d %></td>
        <td><%= transaction.description %></td>
        <td><%= transaction.created_at.strftime('%d/%m/%Y') %></td>
        <td><%= transaction.class %></td>
        <%# <td><%= link_to "Delete", client_destroy_transaction_path(client_id: @client.id, transaction_type: @transaction.class.name.downcase), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this transaction?" } %></td> %>
      </tr>
    <% end %>
  </tbody>
</table>



<%= link_to "Create a transaction", client_transactions_new_path(@client)%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TransactionManagementApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/transactions/index.html.erb
<p>..Find me on app/views/transactions/index...</p>

app/views/transactions/new.html.erb
<h3>New Transaction</h3>

<%= form_with(model: (@expense || @payment), url: @transaction_type == 'expense' ? client_create_expense_path(client_id: @client.id) : client_create_payment_path(client_id: @client.id), method: :post, id: 'transaction-form', local: true) do |f| %>
  <div class="field">
    <%# <%= f.check_box :expense %> %>
    <%# <%= f.label :expense, "expense" %> %>
    <%# <%= f.check_box :payment %> %>
    <%# <%= f.label :payment, "payment" %> %>
    <%= f.label :transaction_type, for: 'transaction_type_select'%>
    <%= f.select :transaction_type, [['Expense','expense'], ['Payment', 'payment']], include_blank: true, class: 'form-control', id: 'transaction_type_select', data: { transaction_type: '' } %>
  </div>

  <div class="field">
    <%= f.label :amount, for: 'transaction_amount' %>
    <%= f.number_field :amount, step: '0.01', class: 'form-control', id: 'transaction_amount' %>
  </div>

  <div class="field">
    <%= f.label :description, for: 'transaction_description' %>
    <%= f.text_area :description, class: 'form-control', id: 'transaction_description' %>
  </div>

  <div class="field">
    <%= f.label :date, for: 'transaction_date'%>
    <%= f.date_select :date, class: 'form-control', id: 'transaction_date' %>
  </div>

  <div class="actions">
    <%= f.submit 'Create Transaction', class: 'btn btn-primary', id: 'submit-button' %>
  </div>
<% end %>


<script>
  document.addEventListener('DOMContentLoaded', function() {
    const form = document.getElementById('transaction-form');
    const transactionTypeSelect = document.getElementById('transaction_type_select');

    if (form && transactionTypeSelect) {
      transactionTypeSelect.addEventListener('change', function() {
        const selectedTransactionType = transactionTypeSelect.value;

        if (selectedTransactionType === 'expense') {
          form.action = '<%= client_create_expense_path(client_id: @client.id) %>';
        } else if (selectedTransactionType === 'payment') {
          form.action = '<%= client_create_payment_path(client_id: @client.id) %>';
        } else {
          alert('Invalid transaction type selected.');
        }
      });
    }
  });
</script>

app/views/transactions/show.html.erb
<p>...Find me on app/views/transactions/show...</p>
<%= @client.transactions %>